// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArticleItem: typeof import('./components/Management/ArticleItem.vue')['default']
    CheckItem: typeof import('./components/Management/CheckItem.vue')['default']
    Comment: typeof import('./components/Comment/Comment.vue')['default']
    CommentItem: typeof import('./components/Comment/CommentItem.vue')['default']
    ConfirmPublish: typeof import('./components/Editor/ConfirmPublish.vue')['default']
    Content: typeof import('./components/Content/Content.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElTag: typeof import('element-plus/es')['ElTag']
    Header: typeof import('./components/Header/Header.vue')['default']
    IEpArrowDown: typeof import('~icons/ep/arrow-down')['default']
    IEpAvatar: typeof import('~icons/ep/avatar')['default']
    IEpBell: typeof import('~icons/ep/bell')['default']
    IEpClose: typeof import('~icons/ep/close')['default']
    IEpEditPen: typeof import('~icons/ep/edit-pen')['default']
    IEpFlag: typeof import('~icons/ep/flag')['default']
    IEpRefresh: typeof import('~icons/ep/refresh')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    IEpTop: typeof import('~icons/ep/top')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    Login: typeof import('./components/Login/Login.vue')['default']
    ManageSlot: typeof import('./components/Management/ManageSlot.vue')['default']
    NewItem: typeof import('./components/Content/NewItem.vue')['default']
    NewsList: typeof import('./components/Content/NewsList.vue')['default']
    PageDevice: typeof import('./components/PageDevice/PageDevice.vue')['default']
    RankHotNews: typeof import('./components/Content/RankHotNews.vue')['default']
    Register: typeof import('./components/Register/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./components/Search/Search.vue')['default']
    SearchContent: typeof import('./components/Content/SearchContent.vue')['default']
    SmartDigest: typeof import('./components/Editor/SmartDigest.vue')['default']
    SmartTitle: typeof import('./components/Editor/SmartTitle.vue')['default']
    UserFunction: typeof import('./components/Content/UserFunction.vue')['default']
    VideoNews: typeof import('./components/Content/VideoNews.vue')['default']
  }
}

export {}
